spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094,localhost:9095,localhost:9096} # 카프카 브로커 주소 (없으면 로컬 기본값)
    consumer:
      auto-offset-reset: earliest # 오프셋 없으면 처음부터 읽음
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 키 역직렬화
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 값 역직렬화
      max-poll-records: 100 # 한번에 최대 100개 메시지 읽음
      enable-auto-commit: false # 수동으로 오프셋 커밋
    producer:
      retries: 3 # 전송 실패 시 3번 재시도
      acks: all # 모든 브로커가 받았을 때 성공으로 처리
      batch-size: 16384 # 배치 크기 16KB
      properties:
        linger-ms: 1 # 1ms 대기 후 배치 전송
    listener:
      ack-mode: manual # 메시지 처리 후 수동으로 커밋

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/${POSTGRES_DB}} # DB 주소 (없으면 로컬 기본값)
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}} # DB 유저
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}} # DB 비밀번호
    driver-class-name: org.postgresql.Driver # PostgreSQL 드라이버

  jpa:
    hibernate:
      ddl-auto: update # 앱 시작 시 테이블 자동 업데이트
    show-sql: false # SQL 로그 출력 안함
    properties:
      hibernate:
        '[format_sql]': false # SQL 포맷팅 안함