# HTTP로 데이터 받는 입력 설정
<source>
  @type http          # HTTP 방식으로 데이터 수신
  port 9880           # 9880 포트에서 수신
  bind 0.0.0.0        # 모든 IP에서 접근 허용
  body_size_limit 32m # 요청 최대 크기 32MB
  keepalive_timeout 10s # 연결 유지 시간 10초
</source>

# kafka.logs 태그로 들어온 데이터를 START_TOPIC으로 전송 (행동 이벤트)
<match kafka.logs>
  @type kafka2
  brokers kafka1:9092
  default_topic "START_TOPIC"

  <buffer>
    @type memory
    flush_interval 1s
    chunk_limit_size 1m
    retry_max_times 1
    retry_wait 2s
    retry_type exponential_backoff
  </buffer>

  <format>
    @type json
  </format>
</match>

# campaign.logs 태그로 들어온 데이터를 CAMPAIGN_TOPIC으로 전송 (캠페인 이벤트)
<match campaign.logs>
  @type kafka2
  brokers kafka1:9092
  default_topic "CAMPAIGN_TOPIC"

  <buffer>
    @type memory
    flush_interval 1s
    chunk_limit_size 1m
    retry_max_times 1
    retry_wait 2s
    retry_type exponential_backoff
  </buffer>

  <format>
    @type json
  </format>
</match>